# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
   include:
   - "*"

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFiles@2
  displayName: 'Copy provisioning scripts'
  inputs:
    SourceFolder: product-aks-cluster-yaml-provisioning/productakscluster-yaml-provisioning/productakscluster
    TargetFolder: '$(build.artifactstagingdirectory)/iac'
    

- task: PublishBuildArtifacts@1
  displayName: 'Publish infrastructure artifacts'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)/iac'
    ArtifactName: iac

- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'Visual Studio Enterprise(ce38cf7c-3580-4375-b891-13a38abb98be)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'product-aks-euw-dev-resgrp'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: '$(build.artifactstagingdirectory)/iac/azuredeploy.json'
    overrideParameters: '-linuxAdminUsername $(linuxAdminUsername) -sshRSAPublicKey "$(sshRSAPublicKey)" -resourceName $(resourceName) -servicePrincipalClientId $(servicePrincipalClientId) -servicePrincipalClientSecret $(servicePrincipalClientSecret) -aadClientAppId $(aadClientAppId) -aadServerAppId $(aadServerAppId) -aadServerAppSecret $(aadServerAppSecret) -aadTenantId $(aadTenantId) -servicePrincipalObjectId $(servicePrincipalObjectId) -networkContributorRoleId $(networkContributorRoleId) -dnsPrefix $(dnsPrefix) -agentCount 3 -kubernetesVersion "1.12.6" -vmssMinInstances 1 -vmssMaxInstances 5'
    deploymentMode: 'Incremental'